### ISSUE TITLE
Allow local currency

### ISSUE THREAD

**Issue by cezarlz** [ebanx/woocommerce-gateway-ebanx#317] opened 2017-02-21 22:10 UTC
### Expected behavior and actual behavior.
Get the local currency from WooCommerce settings options and send to the pay services.

**Comment by gpressutto5** [comment] 2017-02-23 01:32
Duplicate of #285?

**Comment by cezarlz** [comment] 2017-02-23 18:30
@gpressutto5 yes, it was duplicated 😆 thanks bro!

@licianeandreatta another settings that I'm looking for is that:
![image](https://cloud.githubusercontent.com/assets/954889/23273182/c664d194-f9dc-11e6-865e-1a04dd0141b2.png)

The merchant can set the countries that wanna sell. I will take into consideration this woocommerce feature.

**Comment by cezarlz** [comment] 2017-02-23 19:34
We can't get these settings, but this is doing automatically by WooCommerce, please, forget my last comment.

**Closed** 2017-02-23 20:36 UTC
